<?php

if (isset($_GET['id'])) {
    $userID = $_GET['id'];
}

var_export($userID);

if (isset($_GET['id'])) {
    $query = $db->prepare('SELECT * FROM users WHERE id = :id');
    $parameters = [
        'id' => $_GET['id']
    ];
    $query->execute($parameters);
    $users = $query->fetch(PDO::FETCH_ASSOC);
}

// var_dump($users);
?>

<main class="container py-5">
    <h1>
        Modifier un utilisateur
    </h1>
    <form class="mt-5" method="POST" action="logic/edit-user.php">
        <input type="hidden" id="userId" name="userId" value="<?= $userID; ?>" />
        <fieldset>
            <label for="email" class="form-label">Email</label>
            <input type="email" id="email" name="email" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="password" class="form-label">Mot de passe</label>
            <input type="password" id="password" name="password" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="firstName" class="form-label">Prénom</label>
            <input type="text" id="firstName" name="firstName" class="form-control" />
        </fieldset>
        <fieldset>
            <label for="lastName" class="form-label">Nom</label>
            <input type="text" id="lastName" name="lastName" class="form-control" />
        </fieldset>
        <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
    </form>
</main>