<?php



if (isset($_GET['id'])) {
    $query = $db->prepare('SELECT * FROM users WHERE id = :id');
    $parameters = [
        'id' => $_GET['id']
    ];
    $query->execute($parameters);
    $users = $query->fetch(PDO::FETCH_ASSOC);
}

$prenom = $users['first_name'];
$nom = $users['last_name'];
$mail = $users['email'];





?>

<main class="container py-5 text-center">
    <h1><?= $prenom . " " . $nom ?></h1>
    <h2><?= $mail ?></h2>
</main>